[package]
name = "gh-followers"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.28"

[dependencies.tokio]
version = "1.48.0"
features = ["full"]

[dependencies.octocrab]
version = "0.48.0"
features = ["stream"]
